#!/bin/bash -e

mkdir -p _output/bin

sudo docker run \
  --cidfile=cid \
  -v "$PWD":/go/src/github.com/coreos/grafiti:ro \
  -w /go/src/github.com/coreos/grafiti \
  golang:1.8.3-alpine \
  /bin/sh -x -c \
  'apk add --no-cache --update alpine-sdk && make release-binary'

sudo docker cp "$(cat cid)":/go/bin/grafiti _output/bin/grafiti
sudo docker rm "$(cat cid)"
sudo rm cid
